baseurl: /IMI-blog
exclude: ['README.md']
sebastian_weber:
    name: Sebastian Weber
    email: mailto:sebastian.weber1993@aol.com
    bio: Sebastian is a Masters student in Sales & Marketing at the IMC Krems, Austria. He is working for one of the leading IT consultancies in Vienna.
    pic: 'sebastianweber1.jpg'
author_due:
    name: Austin Powers
    email: mailto:nomailyet.com
    bio: This is the co-authors bio.
    pic: 'austinpowers.jpg'